### PR TITLE
Feat/book api

### PR DESCRIPTION
**Pull request by rkumar0099**
Book model, book controller, book routes. Index.js file in Book models is for the new collections that we are adding.
Uploads is a folder to store the book images.

### CODE REVIEW

**Comment by chengmark** [comment]
Could you please follow the current structure, cuz I don't have time to refactor your whole code to fit our codebase

**Comment by chengmark** [comment]
follow the naming convention & file structure that we currently have, I believe that's how you will collaborate in your future work

**Comment by rkumar0099** [comment]
You can check my code again, it follows camel case naming convention. As far as the file structure is concerned and the file names, I will change them. Also, I am a very average programmer. I can't follow up the routes/user/UserController.ts file to code exactly in your style.

**Comment by rkumar0099** [comment]
Also, I believe the TAs will grade our project based on the functionalities our project provides rather than the file structure we follow. I know it is important to have a proper file structure. But I think not everyone is pro here like you bro. So, it is fine to have a very simple file structure without too many directories and files. Like in your style and methodology, we have user folder where we put three files: param.ts, index.ts, usercontroller.ts. In my file structure, we have models folder where all models reside, for example: bookMode.js, chatModel.js, userModel.js, imageModel.js...etc. And then I have controllers folder where all controllers for a specific model reside. bookController.js, chatController.js..etc. And then I have routes folder where all routes for controller reside. I know it may not be an optimal file structure, but it is quite easy to follow especially for average programmer like me.

**Comment by rkumar0099** [comment]
At least this average programmer is trying to contribute to this project as much as possible.

**Comment by chengmark** [comment]
duplicated PR

**Pull request closed without merging**
